import Head from 'next/head'
import { Inter } from 'next/font/google'
// import styles from '@/styles/Home.module.css'
import Script from 'next/script'
import NavBar from './components/navbar'
import Section from './components/Section'
import Footer from './components/Footer'
import Hero from './components/hero'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Next js</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script
        strategy="lazyOnload"
        src={`https://www.googletagmanager.com/gtag/js?id=G-B4H3J9V058`} />
      <Script strategy="lazyOnload">
        {`
         window.dataLayer = window.dataLayer || [];
         function gtag(){dataLayer.push(arguments)};
         gtag('js', new Date());

         gtag('config', 'G-B4H3J9V058');
`} </Script>
    <NavBar></NavBar>
    <main>
    <Section></Section>
    <Hero></Hero>
    </main>
    <Footer></Footer>

    </>
  )
}
